language: generic
sudo: required
services:
  - docker


before_install: 
  - docker build -t kavianba/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kavianba/docker-react npm run test -- --coverage